### ISSUE TITLE
다크모드 전환시 캐러셀의 카드의 위치가 다 망가지는 버그

### ISSUE THREAD

**Issue by 1yoouoo** [Sassy-Project/front-setup#53]
## 📌 Feature Issues
다크모드를 눌러도 캐러셀의 카드위치가 유지되어야함

## ✨ To-do

- [ ] 예상컨데 다크모드 전환시 인라인으로 작성된 스타일이 무시되는 것 같아서 확인해봐야함
- [ ] 다크모드로 변경해도 mbtiCard의 색상을 유지시키면 해결 될 이슈임
- [ ] 카드들의 색상도 다크모드로 적용시키려면 어떻게 버그를 해결할 지 고민해봐야함.
